/**
 * Shield: Terms of Service
 * Basic TOS for AgentDoom's user-generated content platform.
 */

export const TOS_VERSION = '1.0.0'
export const TOS_EFFECTIVE_DATE = '2026-04-01'

export const TERMS_OF_SERVICE = `
# AgentDoom Terms of Service

**Effective Date:** ${TOS_EFFECTIVE_DATE}
**Version:** ${TOS_VERSION}

## 1. Acceptance of Terms

By accessing or using AgentDoom ("the Platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Platform.

## 2. Description of Service

AgentDoom is a platform that enables users to generate, deploy, share, and monetize web-based tools ("Tools") using AI-powered natural language prompts. Tools are generated automatically and hosted on the Platform's infrastructure.

## 3. User Accounts

- You must provide accurate information when creating an account.
- You are responsible for maintaining the security of your account credentials.
- You must be at least 13 years old to use the Platform.
- One person or entity may not maintain more than one free account.

## 4. User-Generated Content

### 4.1 Ownership
You retain ownership of the prompts you submit. Generated Tools are licensed to you under a non-exclusive, worldwide license to use, modify, and distribute.

### 4.2 License to AgentDoom
By creating Tools on the Platform, you grant AgentDoom a non-exclusive, worldwide, royalty-free license to host, display, distribute, and promote your Tools on the Platform and in marketing materials.

### 4.3 Responsibility
You are responsible for the content you generate and share. AI-generated content may contain errors or unexpected outputs. You must review generated Tools before sharing them publicly.

## 5. Prohibited Content and Conduct

You may not use the Platform to generate, host, or distribute:

- **Malware:** Keyloggers, crypto miners, ransomware, trojans, botnets, or any malicious software
- **Phishing:** Fake login pages, credential harvesting tools, or deceptive content designed to steal information
- **Harmful content:** Content promoting violence, self-harm, harassment, hate speech, or discrimination
- **NSFW content:** Sexually explicit material, nudity, or graphic violence
- **Copyright infringement:** Direct reproduction of copyrighted works without authorization
- **Spam:** Mass-generated low-quality content, SEO manipulation tools, or ad injection
- **Privacy violations:** Tools that collect personal information without consent, doxxing tools, or surveillance software
- **Fraud:** Tools designed to deceive users, manipulate financial systems, or facilitate scams

## 6. Content Moderation

- All generated Tools are automatically scanned for policy violations before deployment.
- Tools may be flagged for human review, blocked, or removed at any time.
- Users may report Tools that violate these Terms using the Platform's reporting feature.
- Repeated violations may result in account suspension or termination.

## 7. Rate Limits

- Free accounts: 10 tool generations per hour
- Premium accounts: 50 tool generations per hour
- Rate limits may be adjusted at AgentDoom's discretion.
- Attempting to circumvent rate limits is a violation of these Terms.

## 8. Creator Verification

- Creators may earn a verified badge by meeting Platform criteria (tool count, ratings, identity verification, clean record).
- Verification may be revoked if a creator violates these Terms.
- Verified status does not guarantee immunity from content moderation.

## 9. Monetization

- Verified creators may monetize their Tools through the Platform's marketplace.
- AgentDoom charges a platform fee on marketplace transactions.
- Creators are responsible for applicable taxes on their earnings.
- AgentDoom reserves the right to suspend monetization for creators who violate these Terms.

## 10. Intellectual Property

- AgentDoom's name, logo, and Platform design are proprietary.
- The AI models powering tool generation are licensed, not owned, by AgentDoom.
- You may not reverse-engineer, decompile, or attempt to extract the AI models or Platform source code.

## 11. Disclaimers

- Tools are generated by AI and provided "as is" without warranty.
- AgentDoom does not guarantee the accuracy, safety, or fitness of generated Tools.
- AgentDoom is not liable for damages arising from the use of generated Tools.
- The Platform may experience downtime for maintenance or technical issues.

## 12. Limitation of Liability

To the maximum extent permitted by law, AgentDoom shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Platform.

## 13. Termination

- AgentDoom may suspend or terminate your account at any time for violation of these Terms.
- You may delete your account at any time through account settings.
- Upon termination, your deployed Tools may be removed from the Platform.

## 14. Changes to Terms

AgentDoom reserves the right to modify these Terms at any time. Material changes will be communicated via email or Platform notification at least 30 days before taking effect.

## 15. Governing Law

These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles.

## 16. Contact

For questions about these Terms, contact: legal@agentdoom.ai
`
